### ISSUE TITLE
[Feature Request] Add "Aesthetic Score" to image info and search

### ISSUE THREAD

**Issue by WildBanjos** [doublescale/i2x#2]
Hello. Wanted to put down a small feature request.

Please add the "Aesthetic score" tag as implemented by multiple UI's, extensions, and nodes (notably the old chad scorer which was around since last year, multiple A1111 extensions include [this one](https://github.com/vladmandic/sd-extension-aesthetic-scorer),  the SD.Next fork of A1111, and various nodes in comfyUI). In short, these implementations use a small trained model to assign a score from 1-10 for generated images as an indicator of what the model perceives as more "aesthetic". While the idea is not perfect and has flaws, it is helpful for roughly organizing images by image quality and composition. Also, scoring has been available as some sort of extension since the early days of A1111, so users may have a large amount of historical images with attached score data.

The tag that seems to have been settled on is "Score: x.xx" where x.xx is a number from 1-10 with two decimals.

### Desired Behavior

1. Add the aesthetic score to be listed as a parameter in the infotext
2. Add the ability to search and filter based on score. (Ex: "S:>=5")

Thank you!

**Comment by doublescale** [comment]
Aaa sorry for the late response!  I haven't been checking my notifications here regularly enough lately.

I've never used that extension, but it doesn't sound like it would be too much work to implement this.
Could you attach some sample PNGs (both from A1111 and ComfyUI if you have them handy) with such a score in the metadata that I could test it on?
I see the extension you linked mentions putting the score in the PNG info section and/or EXIF comments.  I'd probably just focus on the PNG info section (I'm assuming it means the text chunks, which i2x already parses), but if you have example files with the EXIF variant too, then those would also be good to have for reference.

If I add a numeric-range search filter like that, then this might also be an opportunity to do the same for filtering by width/height and CFG, which I had meant to do sometime anyways!

**Comment by WildBanjos** [comment]
Not a problem!

Attached is a simple sample image with the score generated from A1111. It does appear to utilize the standard PNG info section (quoted below in case). Unfortunately, I was not able to generate one with ComfyUI. It seems like there isn't one well known custom node to implement the score, there's a few unmaintained ones and was unable to get one running. (An aside, it looks like most of the nodes only output a value, so assuming users would manually utilize another node to append it to the PNG info if desired). Given that, seems like the only working implementations of the score I see are in the A1111 ecosystem and SD.NEXT.

Regardless, adding filtering by other parameters sounds fantastic as well.


![00509-1429433092](https://github.com/doublescale/i2x/assets/117058715/42d2b924-98da-4113-9a67-423561949232)
`"parameters": "photo of duck wearing tophat\nSteps: 20, Sampler: Euler a, CFG scale: 7, Seed: 1429433092, Size: 512x512, Model hash: 7f6146b8a9, Model: edgeOfRealism_eorV20Fp16BakedVAE, Token merging ratio: 0.2, NGMS: 3, Version: 1.5.0, Score: 5.89"`

**Comment by doublescale** [comment]
Thank you!  Looks like that picture you attached kept its metadata, so I was able to test with that no problem.
I have pushed a [change](https://github.com/doublescale/i2x/commit/c4eed52f3d3db07b79c3dd80e45d6d7966b8839a) that displays that score already since it was very simple to do.
You could `git pull` and `./build` again, hopefully it'll work for you.
I'll implement the search-filtering some time later.

Also I added out a little commented-out section that might be useful to you for such things in the future: If you search src/main.c for "All parameters", you'll see an `#if 0` above it, currently at [line 4581](https://github.com/doublescale/i2x/blob/c4eed52f3d3db07b79c3dd80e45d6d7966b8839a/src/main.c#L4581).  If you change that to `#if 1` and rebuild, it'll display the entire block of parameters that you pasted under the image in your message, including "Token merging ratio" etc., in the info panel.
It's probably going to be unusable for ComfyUI's JSON metadata, but it might let you see some of these other A1111 parameters that i2x doesn't look for.
Maybe at some point I could properly build this into the UI, but for now I'll keep it as a hack like this.

@WildBanjos, question:  Is it OK if I include that image as part of i2x's repository, to have as a test case?

**Comment by WildBanjos** [comment]
Absolutely fantastic! Built the latest version and score displays great. Thank you! Even tested the "all parameters" change and can confirm that works.

Also, you are welcome to include that image in the repo as a testcase. 👍

**Comment by doublescale** [comment]
Commit 06e72474d0d835110e3058468ecd55ed9dbf3d43 implements numeric search.
You can search for images with a score of at least five with "score:>=5".  Simple ranges are also possible, e.g. "score:>=3 score:<9", but no disjoint ones (no way to search for score under 3 *or* above 9; you can, however, exclude a single exact number with e.g. "-score:=5"), at least for now.
Other than "score", new search keywords are "width", "height", "aspect" (width/height), "steps", "cfg".
See the help (F1, then Tab) for details.

@WildBanjos: Let me know if you encounter any bugs!

**Comment by doublescale** [comment]
Also, that duck is adorable.  He's in the repo now.  I like ducks

**Comment by WildBanjos** [comment]
Just pulled/built/tested the latest, and can say the search for the values works great! Filtering by score is fantastic and already even gives some interesting perspectives on my gens. This is awesome, thank you!

Glad you like the duck :) 

One minor issue was with the aspect ratio search. While it's not relevant to this issue (I can make another GH issue if you want), it looks like the formula used to calculate the ratio requires the full significant digits. For example, the classic 512x768 and it's upscales will only show up in search if the full "0.66666667" is typed out. That is not ideal. However, I'm hesitant to request rounding to 1 or 2 digits are since I'm not sure what the standards are for rounding decimal aspect ratios.

**Comment by doublescale** [comment]
You're right, I didn't think through aspect-ratio-filtering entirely.
Change 8960bd3e08371646953249de602ceb6e18ada399 should hopefully help:
- You can do divisions and multiplications for the value now, e.g. `aspect:=512/768` or `aspect:=2/3`. In this case, a tolerance of 0.1% also gets added to equality comparisons (I'm not sure about the best way to apply tolerance here either).
- For looser matches, I added a `~=` operator with 10% tolerance, e.g. `score:~=6` will match a score between 5.4 and 6.6.
- Since I added multiplication, I also added a `pixelcount` search value (width*height, like for sorting), so you can find big images with varying aspect ratios like `pixelcount:>=1024*1024`.

@WildBanjos: Tell me if anything is still short of ideal, otherwise feel free to close the issue!

**Comment by WildBanjos** [comment]
Just tested the change. Honestly, it all works great. 

Allowing the math in the value makes a big difference. So far in my testing this works as expected, allowing all images of a ratio, even if it's scaled up or down, to show up. 

Also, the ~= operator works great as well. 

Thanks!

**Comment by doublescale** [comment]
I'm glad to hear it works!
