### ISSUE TITLE
[Feature Request] Add different sorting methods, and way to designate default at launch.

### ISSUE THREAD

**Issue by WildBanjos** [doublescale/i2x#3]
Hello. Wanted to put down a small QoL item.

### Current behavior:
Currently when launching in a directory, the viewer shows all files sorted from oldest to newest (or perhaps it's alphabetical based on filenames). To see recent generations, you must either scroll down to bottom or use the "jump to" key to jump to last.

### New behavior
Would add new key command (perhaps "S" for sort), to rotate through sorting methods. 

Further, would also add a flag when invoking the program to set the default sorting method at startup (ex: i2x -s 'newest' /path/)

Potential sorting methods relevant for image generation:

- Newest Modified
- Oldest Modifed
- Largest filesize (may be helpful for finding upscaled/large images)
- Smallest filesize
- Alphabetical based on Model name
- Aesthetic score as mentioned in #2 

Thank you!

**Comment by doublescale** [comment]
By default the program sorts the images alphabetically by filename, using the C standard library's `strcmp`, which I *think* might be locale-dependent.

And yeah, I meant to add different sorting options like you suggest at some point, but I ended up being lazy and content enough with the work-around of calling i2x with a sorted parameter list, such as `i2x $(ls -t *.png)` for newest-first (`ls` has all sorts of sorting options)... although now that I think about it, that probably doesn't work with paths containing spaces.
Maybe you could use something like this in the meanwhile too.

Now that I know that someone else is also using the program and wants this, I'll probably add this feature for real :D
I'm not sure when I'll have time to get to this though; it'll need some work to be done properly, considering interactions with search-filtering, and the asynchronous loading of metadata (Getting a directory listing of filenames is *much* faster than reading the headers of all the image files, so i2x can sort based on them right away, but sorting by e.g. model name requires reading a little bit of each file first.  I'd like to keep startup instant when possible.).

**Comment by doublescale** [comment]
Oh, and as a note to myself, this would be a good opportunity to add the file's timestamp and size to the info-panel too.

**Comment by doublescale** [comment]
Thinking about sorting by **model name** specifically, I'd think that you might want additional features to really make the most of it, because unlike the other properties, I would expect many images to have the same model:

- Sort on multiple properties, perhaps hard-coded (e.g. sort by model primarily, then use filename as a tie-breaker), or explicitly let the user choose multiple levels of sorting.
- Group the results, having little labeled breaks between thumbnails belonging to the same model. I had considered doing something like this for grouping by prompt or seed, but never got around to it.

@WildBanjos, for your personal use-case, how did you imagine sorting by model name to behave?  Implementing just some hard-coded tie-breakers would likely be the least complicated, but if sorting by model is something you'd make heavy use of, it might be worth considering these other things too.

Note that you can also filter by models with `m:modelToInclude` and `-m:modelToExclude` in the search.  That's what I've been doing in my own collections.

**Comment by WildBanjos** [comment]
Thanks for the response, that gives me a lot to think about. Honestly, being able to pipe in specific files and pre-sort does open up some options. However I think for default use being able to point it at a directory with some flags would be good for the long run.

I see the point about reading into the file affecting startup time. Keeping the current behavior (or one of the low latency options) would work as the default. However, I think a disclaimer in the helpfile that any sorting options that require reading PNG info will affect startup time should be fine. I mean for a very large library that would take a moment, but anyone running a image collection program with a large library would expect it to take a breath while loading.

As for the sorting. My personal use case would probably find the labeled breaks between 'sections' the most useful when sorting by model. When I open the program with these flags, I would want to see the "comparison" of generation usage/quality between the various models. Theoretically, the labeled breaks could be a flag itself and as you mentioned would be useful for other parameters. Being able to specify the "tie-breaker" makes sense for flexibility, but I would be happy with filename or date hardcoded (if sorting by model or something else as the 1st level).

**Comment by doublescale** [comment]
Commit 074901d42e6651c9fdf7a4c54488ef2df098234d implements sorting.  No grouping yet.
You can sort by filepath (default, as before, except now it uses a naive lexicographic ordering of the path's bytes instead of whatever `strcmp` does), last modification time, filesize, random shuffle, total pixels (width*height), prompt, model, score.
All modes allow for ascending & descending order.

For the initial specification of the ordering, I went for an environment variable (see `i2x --help`), similarly to the other existing settings, instead of a command-line argument, since I prefer them for a few reasons:
- Less parsing work needed in my code
- Avoids problems with tricky filenames (like if a file is literally called "-s", you'd have to do something like `i2x <options> -- <files>` and it's just inconvenient)
- Allows setting a personal default conveniently e.g. in your ~/.bashrc (although options could be set with an `alias` too)

If your use-case would be made more comfortable by a command-line argument, I'll implement it, but maybe you'll be happy with this too.

When specifying an initial ordering that relies on metadata (total pixels, prompt, model, score), i2x will block at start-up until all metadata has been parsed.

You can select a sort order at runtime too, with Shift+S.
Instead of cycling through all possible modes (since there's so many modes), I made it a modal interaction, so you'll have to hit another key afterwards to select the mode, with shift held for descending order instead of ascending.  You can use the cursor keys to select a mode, too.
Hit Escape or Enter to close the sorting modal.

Also, file size and modification time is shown in the info panel now.

@WildBanjos, let me know if this works for you, and if you encounter any bugs.  I haven't tested this extensively yet, and the code is a bit convoluted, so I may have missed a few things.

**Comment by WildBanjos** [comment]
Just pulled/built/tested the latest, and all the sorting seems to work as expected. Works great, thank you! I don't see any bugs so far. I have no issue with setting env variables rather than command line arguments. I get how adding arguments can just add complexity both to the ease of the experience and to the internals.

I only have two minor UX comments with the sorting modal at runtime. Neither of these are serious issues or bugs, just QoL items I noticed.
1. Using _escape_ to close the modal is awkward as the first press of _esc_ closes the modal, but holding down too long or accidentally pressing it again closes i2x entirely. Using _enter_ works fine though. I think you could remove/block the _esc_ action while the modal is up and just stick to _enter_ to exit the modal.
2. When changing sorting modes, it keeps the current selected image and jumps to where the current image would be in the new sort. For ex: sorting by pixelcount with the intent to find the largest images requires scrolling back to the top. It would seem to be more useful if when changing sorting modes it would jump to the 1st item in the gallery so the user can immediately see the effect of the the new sort order. However, I know this is far from a standard in different programs(file/image/etc managers, I've seen everything) so am unsure if my recommendation is reasonable or a common sentiment.

Also, on a different note, I hope this feedback is helpful. Don't want it to come off like trying to nitpick your project.

**Comment by doublescale** [comment]
I'm glad to hear it's working!

### Regarding 1:
I'd rather keep Escape to close those modals since I prefer it personally.  The search-filter modal also uses Escape, and has different behavior for it than Enter (Escape clears the filter (but still keeps the search string), Enter keeps the filter applied).
I agree that Escape closing the program is awkward sometimes though.  I actually added a sort of safety, in case you have marked images, then Escape doesn't close the window.
It might be nice to save the UI state on exit so it can be brought back up quickly again, but that would be tricky to implement well and would still throw the user out of the flow.

I could just remove the Escape binding to exit i2x entirely, leaving Ctrl+Q and closing via window manager (Alt+F4, clicking the X icon, etc.) which are hopefully less likely to be accidentally pressed.
What do you think?

### Regarding 2:
I wasn't sure what the best image-selection after a sorting- or filtering-change would be either.
One advantage that the current implementation has is that the user can explore the neighborhood of their current image, and go back to previous sorting modes without losing their place.  Seeing the first image in the new sort order is two keystrokes away (`Enter`, `Home`), which I agree is not the best for quickly glancing at the top-sorted results.  Maybe I could make `Home` etc. work while the modal is open as a compromise.

If I change the behavior to change the viewed image, there would currently be no way to get back to the previously viewed image.
Ideally, it should keep a history of such jumps so this would be undo-able.

Actually, after thinking about this aloud, maybe the best compromise for now would be to make it similar to the search-filter modal behavior:  Show the top image immediately when changing sort orders, keep that result when pressing Enter, and revert to the old sort order and selection when pressing Escape.
That would make it harder to explore the current image's newly sorted neighborhood (it could still be done by marking, showing only marked, sorting, then clearing the mark-filter), but honestly that's probably not a frequent use-case anyways.
Maybe I'll go for this and see how it feels!

**Comment by doublescale** [comment]
Change c02760928d08263126f183d17b2c2cde2cfb7a66 implements this behavior, showing the top results immediately on sort order change, but allows canceling it with Escape.  I think I like it, personally!

You can also now use some of the navigation keys while the sort modal is open (not Left/Right, those are used by the modal).

**Comment by doublescale** [comment]
Commit 0f95b128e5f2c77121400a3b6073728286504b62 also makes the Escape in the search-filter behave more like a proper "cancel" of the operation, to make it more consistent with this sort-canceling.

**Comment by doublescale** [comment]
> Also, on a different note, I hope this feedback is helpful. Don't want it to come off like trying to nitpick your project.

Somehow I had missed that note until now, sorry!
I definitely appreciate your feedback;  just knowing that there's at least a third person using i2x (other than myself and a friend of mine) gave me the motivation I needed to implement some things that I had been wanting for myself anyways :D
Coincidentally, some of the structure changes that I did to implement some of these sort modes in particular have lead me to see ways to make file-refreshing more robust... I'll have to do some more testing, but hopefully it should crash less often now.

**Comment by doublescale** [comment]
Commit f94bb6fbc1cd1ee6755efbc2ffbaadefb62f8249 implements some basic thumbnail grouping functionality.  Hit Ctrl+G, then select between date/prompt/model grouping.
This is independent of sorting;  all consecutive images having the same property get collected into a group with a heading.

![image](https://github.com/doublescale/i2x/assets/30209702/6d41d992-6986-4b28-9e4f-c7d5ac5b625d)

I have some ideas to improve it still (a major thing would be to highlight prompt differences), but do tell me if you expected different behavior, or if there are other things that you'd find useful to group by (like by month, hour, score rounded to some precision, maybe a combination of properties, etc.).

**Comment by WildBanjos** [comment]
Wow, still testing out the newest commits. Definitely really like what what's been done.

> Change c027609 implements this behavior, showing the top results immediately on sort order change, but allows canceling it with Escape. 

Fantastic! That That seems to be the best of both options.

> Commit 0f95b12 also makes the Escape in the search-filter behave more like a proper "cancel" of the operation, to make it more consistent with this sort-canceling.

Works great from my testing.

> Commit f94bb6f implements some basic thumbnail grouping functionality. 

Fantastic. It took a little getting used to. Doing a full group by model for example requires bringing up the sort modal to sort by model AND the grouping modal. This isn't a major hassle though, the end result is great. 

> I'd rather keep Escape to close those modals since I prefer it personally. I could just remove the Escape binding to exit i2x entirely, leaving Ctrl+Q and closing via window manager (Alt+F4, clicking the X icon, etc.) which are hopefully less likely to be accidentally pressed.

Hmm. Ctrl+Q is one of the common keybinds that are used to exit a program, that plus the any other GUI or system-wide methods should leave sufficent options for users to exit. For consistency, ESC doesn't automatically exit most other desktop programs, and my thoughts lean towards removing it.

> I definitely appreciate your feedback

Glad it's helpful :)

**Comment by doublescale** [comment]
I'm happy you're liking it!

> Fantastic. It took a little getting used to. Doing a full group by model for example requires bringing up the sort modal to sort by model AND the grouping modal. This isn't a major hassle though, the end result is great.

True, it could be streamlined a bit more.  I was considering having a shared modal for sort and group options so you don't have to close and re-open modals.  At the very least I should add a way to start up with a grouping mode, like the env-var for sorting, the next time I dig into this.

> ... ESC doesn't automatically exit most other desktop programs, and my thoughts lean towards removing it.

Done!  Starting with commit 88f523f8b63167401c045d7e7008d724675190f7, Escape won't quit the program anymore.

**Comment by WildBanjos** [comment]
> Done! Starting with commit https://github.com/doublescale/i2x/commit/88f523f8b63167401c045d7e7008d724675190f7, Escape won't quit the program anymore.

Awesome. Pulled and built the latest. Works fantastic! Thank you. I'll go ahead and close this issue since it looks like you added everything in terms of sorting.
